name = "PXR Direwolf20 v11"
author = "PixelRaid Development Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9307baf97efc6b76815765cfa08bc7cbfc79b5ee3bca8da121a274172f45636"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.74"
